
server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ikzspbdcwuyfum:c96b6cc3b645886176056ba7680437add46d13060b509f00dc11c6863be42e1e@ec2-3-233-43-103.compute-1.amazonaws.com:5432/dfmf658annb9ga
    username: ikzspbdcwuyfum
    password: c96b6cc3b645886176056ba7680437add46d13060b509f00dc11c6863be42e1e
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para aprendizado
  version: 1.0
